package com.arjental.dealdone.models

import java.util.*

class StartListModel {

//    val list = listOf(
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "First",
//            priority = TaskItemPriorities.HIGH,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "Second",
//            priority = TaskItemPriorities.HIGH,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = true,
//            text = "Third",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "Fourth",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = true,
//            text = "Fifth",
//            priority = TaskItemPriorities.NONE,
//            deadline = 1624647400000L,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "Six",
//            priority = TaskItemPriorities.NONE,
//            deadline = 1624647600000L,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = true,
//            text = "Sven",
//            priority = TaskItemPriorities.NONE,
//            deadline = 1624647800000L,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrstlast",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.NONE,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "FIrst",
//            priority = TaskItemPriorities.MEDIUM,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        ),
//        TaskItem(
//            id = UUID.randomUUID(),
//            isSolved = false,
//            text = "Lasty",
//            priority = TaskItemPriorities.HIGH,
//            state = ItemState.EXIST,
//            createDate = 1624647400000L,
//        )
//    )

}